on: push

name: Linux Build

jobs:
  # 32-bit, clang
  build32:
    runs-on: ubuntu-latest
    env:
      CFLAGS: -m32
      CC: clang
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: sudo apt-get install clang
      - run: ./bootstrap
      - run: ./configure --enable-remote-bitbang --enable-jtag_vpi --disable-target64
      - name: Save config.log
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          path: config.log
      - run: make
      - run: file src/openocd


  # 64-bit, gcc
  build64:
    runs-on: ubuntu-latest
    env:
      CFLAGS: -m64
      CC: gcc
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: ./bootstrap
      - run: ./configure --enable-remote-bitbang --enable-jtag_vpi
      - run: make
      - run: file src/openocd
